language: node_js
node_js:
    - "node"
services:
    - postgresql
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/tape/bin/tape --reporter lcovonly -- -R spec
  - codecov
